### PR TITLE
Adds deploy and deploy:prod commands and updates circle config 

### PR DESCRIPTION
**Pull request by bennett000**

### CODE REVIEW

**Comment by smithad15** [comment]
Hadn't set this up properly yet, but you'll need it: https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs

**Comment by bennett000** [comment]
@smithad15 thanks... still uber new to CI 2

**Comment by smithad15** [comment]
Makes two of us. Was my first shot at using the new workflows

**Comment by bennett000** [comment]
Hope you don't mind the self :shipit: , but it's late and I need to merge this to see if it deploys

**Comment by smithad15** [comment]
I figure both of us will be doing some self :shipit:s for this one due to time constraints

**Pull request merged**
